package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.List;

/*
 * Boundary per la scelta della ClasseVirtuale dopo il login.
 *
 * Il Boundary possiede il proprio JDialog modale (vedi apriDialog).
 * Modale rispetto al frame di login: e' una scelta "secondaria" sopra
 * al login e blocca il flow finche' l'utente non sceglie o annulla.
 * Su Annulla / X il dialog si chiude da solo; su Conferma chi ha
 * registrato addConfermaListener decide cosa fare e chiama
 * chiudiDialog() per chiuderlo.
 *
 * Viene chiamato indipendetemente da ServiziStudente o ServiziDocente, una volta
 * inseriti nome e cognome dell'Utente.
 *
 * Viene popolato SOLO con le classi relative a quell'Utente
 */
public class FormSceltaClasse {
    private JPanel panel1;
    private JComboBox<String> comboClasse;
    private JButton buttonAnnulla;
    private JButton buttonConferma;

    /*
     * JDialog "di proprieta'" di questo Boundary, creato in apriDialog().
     * Tenerlo come campo permette di chiuderlo dal listener Annulla
     * registrato nel costruttore e dal metodo pubblico chiudiDialog().
     */
    private JDialog dialog;

    public FormSceltaClasse() {
        // Annulla: chiude solo il dialog; il login resta a disposizione.
        buttonAnnulla.addActionListener(e -> {
            if (dialog != null) dialog.dispose();
        });
    }

    public JComponent getPanel() {
        return panel1;
    }

    /*
    Metodo utilizzato nei Form Docente/Studente, prende la Lista delle classi
    associate a quell'Utente, tramite la ricerca filtrata dei Facade Orchestrati dai controller
     */

    public void setClassi(List<String> classi) {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String c : classi) {
            model.addElement(c);
        }
        comboClasse.setModel(model);
    }

    public String getClasseSelezionata() {
        return (String) comboClasse.getSelectedItem();
    }

    public void addConfermaListener(ActionListener listener) {
        buttonConferma.addActionListener(listener);
    }

    /*
     * Apre il JDialog modale rispetto al parent. Bloccante: il chiamante
     * resta fermo qui finche' il dialog non viene chiuso (Annulla, X o
     * Conferma seguito da chiudiDialog).
     */
    public void apriDialog(JFrame parent) {
        dialog = new JDialog(parent, "Seleziona Classe", Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setContentPane(panel1);
        dialog.setSize(420, 240);
        dialog.setLocationRelativeTo(parent);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setVisible(true);
    }

    /*
     * Chiamato dal listener Conferma esterno dopo aver letto la classe
     * scelta, per chiudere il dialog. L'API esterna evita di esporre
     * il JDialog stesso.
     */
    public void chiudiDialog() {
        if (dialog != null) dialog.dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 1, new Insets(25, 30, 25, 30), 0, 20));
        final JLabel labelTitolo = new JLabel();
        labelTitolo.setFont(new Font("SansSerif", Font.BOLD, 20));
        labelTitolo.setText("Seleziona la Classe");
        panel1.add(labelTitolo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panelScelta = new JPanel();
        panelScelta.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 15, 0));
        panel1.add(panelScelta, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel labelClasse = new JLabel();
        labelClasse.setFont(new Font("SansSerif", Font.PLAIN, 14));
        labelClasse.setText("Classe:");
        panelScelta.add(labelClasse, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboClasse = new JComboBox();
        comboClasse.setFont(new Font("SansSerif", Font.PLAIN, 14));
        panelScelta.add(comboClasse, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panelBottoni = new JPanel();
        panelBottoni.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 15, 0));
        panel1.add(panelBottoni, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonAnnulla = new JButton();
        buttonAnnulla.setFont(new Font("SansSerif", Font.PLAIN, 14));
        buttonAnnulla.setText("Annulla");
        panelBottoni.add(buttonAnnulla, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(120, 35), null, 0, false));
        buttonConferma = new JButton();
        buttonConferma.setFont(new Font("SansSerif", Font.BOLD, 14));
        buttonConferma.setText("Conferma");
        panelBottoni.add(buttonConferma, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(140, 35), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}