package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import entity.ClasseVirtuale;
import entity.Docente;

import javax.swing.*;
import java.awt.*;

/*
 * Form principale del flow docente.
 *
 * In alto: bottone "Indietro" (torna al login docente).
 * Sotto: due JToggleButton ("Aggiorna Registro" / "Consulta Registro")
 * raggruppati in ButtonGroup (uno sempre selezionato).
 * In basso: un pannello "contenuto" che mostra alternativamente il
 * sotto-pannello di aggiornamento (FormAggiornaRegistro) o di
 * consultazione (FormConsultaRegistro).
 */
public class FormGestioneRegistro {

    private JPanel panel1;
    private JButton buttonBack;
    private JToggleButton toggleAggiorna;
    private JToggleButton toggleConsulta;
    private JPanel panelContenuto;

    /*
     * Sotto-pannelli del parent.
     * - formAggiorna: delegato a FormAggiornaRegistro (sub-toggle bar
     *   Lezione/Compito/Valutazione + form di inserimento, listener Salva
     *   gestiti internamente).
     * - formConsulta: delegato a FormConsultaRegistro (sub-toggle bar
     *   Lezioni/Compiti/Monitora + form di monitoraggio, listener Mostra
     *   gestito internamente).
     */
    private final FormAggiornaRegistro formAggiorna = new FormAggiornaRegistro();
    private final FormConsultaRegistro formConsulta = new FormConsultaRegistro();

    /*
     * JFrame "di proprieta'" del Boundary, creato in apriGestioneRegistro().
     * Tenerlo come campo permette al back listener (registrato nel
     * costruttore) di chiuderlo al momento del click.
     */
    private JFrame frame;

    public FormGestioneRegistro() {

        ButtonGroup gruppo = new ButtonGroup();
        gruppo.add(toggleAggiorna);
        gruppo.add(toggleConsulta);

        // Stato iniziale: vista "Aggiorna" attiva
        toggleAggiorna.setSelected(true);
        mostraSotto(formAggiorna.getPanel());

        /*
        A seconda della selezione del Toggle, verrà chiamato il Panel del Caso D'Uso selezionato
         */
        toggleAggiorna.addActionListener(e -> mostraSotto(formAggiorna.getPanel()));
        toggleConsulta.addActionListener(e -> mostraSotto(formConsulta.getPanel()));

        /*
         * Back: chiudo questa finestra e riapro il login docente. La lambda
         * legge il campo `frame` al momento del click — apriGestioneRegistro
         * lo avra' gia' valorizzato.
         */
        buttonBack.addActionListener(e -> {
            frame.dispose();
            new FormServiziDocente().apriFormServiziDocente();
        });
    }

    /*
     * Entry point del Boundary. Setta la classe sui due sotto-form (che
     * cosi' popolano combo studenti / Lezioni / Compiti tramite il
     * controller static), crea il JFrame e lo mostra.
     *
     * Chiamato da FormServiziDocente dopo la conferma classe.
     */
    public JFrame apriGestioneRegistro(Docente docente, ClasseVirtuale classe) {

        formAggiorna.setClasse(classe);
        formConsulta.setClasse(classe);

        frame = new JFrame("Gestione Registro — " + classe.getNome());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(panel1);
        frame.setSize(600, 450);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    public JComponent getPanel() {
        return panel1;
    }

    /*
     * Sostituisce il contenuto di panelContenuto con il sotto-pannello
     * richiesto. revalidate + repaint sono necessari perche' stiamo
     * cambiando i figli di un container gia' visibile.
     */
    private void mostraSotto(JComponent sotto) {
        panelContenuto.removeAll();
        panelContenuto.add(sotto, BorderLayout.CENTER);
        panelContenuto.revalidate();
        panelContenuto.repaint();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 1, new Insets(25, 30, 25, 30), 0, 10));
        buttonBack = new JButton();
        buttonBack.setFont(new Font("SansSerif", Font.PLAIN, 12));
        buttonBack.setText("Indietro");
        panel1.add(buttonBack, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(80, 24), null, 0, false));
        final JPanel togglebar = new JPanel();
        togglebar.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 8, 0, true, false));
        panel1.add(togglebar, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        toggleAggiorna = new JToggleButton();
        toggleAggiorna.setFont(new Font("SansSerif", Font.BOLD, 12));
        toggleAggiorna.setText("Aggiorna Registro");
        togglebar.add(toggleAggiorna, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(130, 26), null, 0, false));
        toggleConsulta = new JToggleButton();
        toggleConsulta.setFont(new Font("SansSerif", Font.BOLD, 12));
        toggleConsulta.setText("Consulta Registro");
        togglebar.add(toggleConsulta, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(130, 26), null, 0, false));
        panelContenuto = new JPanel();
        panelContenuto.setLayout(new BorderLayout(0, 0));
        panelContenuto.setBorder(BorderFactory.createLineBorder(new Color(-3355444)));
        panel1.add(panelContenuto, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
