package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.GestoreServiziStudente;
import entity.ClasseVirtuale;
import entity.Studente;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class FormServiziStudente {
    private JPanel panel1;
    private JTextField fieldNome;
    private JTextField fieldCognome;
    private JLabel labelErrore;
    private JButton buttonConferma;

    /*
     * JFrame "di proprieta'" del Boundary, creato in apriFormServiziStudente().
     * Tenerlo come campo permette al listener Conferma (registrato nel
     * costruttore) di chiuderlo prima di aprire il profilo.
     */
    private JFrame frame;

    public FormServiziStudente() {

        /*
         * Listener Conferma: le guardie sugli input (campi vuoti, studente
         * non trovato, lista classi vuota) stanno qui nel Boundary; il
         * Controller assume input gia' validato (pattern professore).
         * Su successo apre il popup FormSceltaClasse modale, e sulla scelta
         * apre il profilo.
         */
        buttonConferma.addActionListener(e -> {

            pulisciErrore();

            String nome = fieldNome.getText().trim();
            String cognome = fieldCognome.getText().trim();

            if (nome.isEmpty() || cognome.isEmpty()) {
                mostraErrore("Inserire nome e cognome");
                return;
            }

            Studente studente = GestoreServiziStudente.cercaStudente(nome, cognome);
            if (studente == null) {
                mostraErrore("Studente non trovato");
                return;
            }

            /*
            Questo richiama la ricerca filtrata Custom creata da noi nel
            GestorePersistenza, tramite questo meccanismo

            GestoreServiziStudente (Controller) -> GestoreVisualizzazione (Entity) ->
            GestorePersistenza(Database)

             */

            List<ClasseVirtuale> classi = GestoreServiziStudente.classiDi(studente);
            if (classi.isEmpty()) {
                mostraErrore("Nessuna classe associata a questo studente");
                return;
            }

            apriSceltaClasse(studente, classi);
        });
    }

    /*
     * Apre il popup FormSceltaClasse modale rispetto al frame di login.
     * Su Conferma: chiude dialog + login, apre il profilo. Su Annulla:
     * solo dispose del dialog (gestito internamente al FormSceltaClasse),
     * il login resta a disposizione per riprovare.
     */
    private void apriSceltaClasse(Studente studente, List<ClasseVirtuale> classi) {
        FormSceltaClasse formScelta = new FormSceltaClasse();
        formScelta.setClassi(classi);
        formScelta.addConfermaListener(e -> {
            ClasseVirtuale scelta = formScelta.getClasseSelezionata();
            formScelta.chiudiDialog();
            frame.dispose();

            /*
            Quando tutto va a buon fine, apre il Form di Visualizzazione del Profilo
            permettendo il corretto svolgimento del Caso D'Uso
             */

            new FormVisualizzazioneProfilo().apriProfilo(studente, scelta);
        });
        formScelta.apriDialog(frame);
    }

    /*
     * Entry point del Boundary. Crea il JFrame, lo mostra; il listener
     * Conferma (registrato nel costruttore) prende in carico il resto.
     */
    public JFrame apriFormServiziStudente() {
        frame = new JFrame("Accesso Studente");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(panel1);
        frame.setSize(500, 400);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    public void mostraErrore(String messaggio) {
        labelErrore.setText(messaggio);
    }

    public void pulisciErrore() {
        labelErrore.setText(" ");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 1, new Insets(25, 30, 25, 30), 0, 20));
        final JLabel labelTitolo = new JLabel();
        labelTitolo.setFont(new Font("SansSerif", Font.BOLD, 24));
        labelTitolo.setText("Accesso Studente");
        panel1.add(labelTitolo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), 15, 12));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel labelNome = new JLabel();
        labelNome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        labelNome.setText("Nome:");
        panel2.add(labelNome, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldNome = new JTextField();
        fieldNome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        panel2.add(fieldNome, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(250, 30), null, 0, false));
        final JLabel labelCognome = new JLabel();
        labelCognome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        labelCognome.setText("Cognome:");
        panel2.add(labelCognome, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldCognome = new JTextField();
        fieldCognome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        panel2.add(fieldCognome, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(250, 30), null, 0, false));
        labelErrore = new JLabel();
        labelErrore.setFont(new Font("SansSerif", Font.ITALIC, 13));
        labelErrore.setForeground(new Color(-65536));
        labelErrore.setText(" ");
        panel1.add(labelErrore, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonConferma = new JButton();
        buttonConferma.setFont(new Font("SansSerif", Font.BOLD, 16));
        buttonConferma.setText("Conferma");
        panel1.add(buttonConferma, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 45), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
