package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

public class FormServiziDocente {
    private JPanel panel1;
    private JTextField fieldNome;
    private JTextField fieldCognome;
    private JLabel labelErrore;
    private JButton buttonConferma;

    public JComponent getPanel() {
        return panel1;
    }

    public String getNomeInserito() {
        return fieldNome.getText().trim();
    }

    public String getCognomeInserito() {
        return fieldCognome.getText().trim();
    }

    public void mostraErrore(String messaggio) {
        labelErrore.setText(messaggio);
    }

    public void pulisciErrore() {
        labelErrore.setText(" ");
    }

    public void addConfermaListener(ActionListener listener) {
        buttonConferma.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 1, new Insets(25, 30, 25, 30), 0, 20));
        final JLabel labelTitolo = new JLabel();
        labelTitolo.setFont(new Font("SansSerif", Font.BOLD, 24));
        labelTitolo.setText("Accesso Docente");
        panel1.add(labelTitolo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), 15, 12));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel labelNome = new JLabel();
        labelNome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        labelNome.setText("Nome:");
        panel2.add(labelNome, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldNome = new JTextField();
        fieldNome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        panel2.add(fieldNome, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(250, 30), null, 0, false));
        final JLabel labelCognome = new JLabel();
        labelCognome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        labelCognome.setText("Cognome:");
        panel2.add(labelCognome, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldCognome = new JTextField();
        fieldCognome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        panel2.add(fieldCognome, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(250, 30), null, 0, false));
        labelErrore = new JLabel();
        labelErrore.setFont(new Font("SansSerif", Font.ITALIC, 13));
        labelErrore.setForeground(new Color(-65536));
        labelErrore.setText(" ");
        panel1.add(labelErrore, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonConferma = new JButton();
        buttonConferma.setFont(new Font("SansSerif", Font.BOLD, 16));
        buttonConferma.setText("Conferma");
        panel1.add(buttonConferma, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 45), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}