package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.GestoreServiziDocente;
import entity.ClasseVirtuale;
import entity.Docente;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/*
 * Boundary del login docente. Speculare a FormServiziStudente: stessa
 * struttura del .form (nome+cognome+errore+conferma)
 *
 * Controlla tramite guardie l'inserimento di nome+cognome, chiama la scelta
 * della classe popolando la comboBox grazie al controller
 */
public class FormServiziDocente {
    private JPanel panel1;
    private JTextField fieldNome;
    private JTextField fieldCognome;
    private JLabel labelErrore;
    private JButton buttonConferma;

    /*
     * JFrame "di proprieta'" del Boundary, creato in apriFormServiziDocente().
     * Tenerlo come campo permette al listener Conferma di chiuderlo prima
     * di aprire la gestione registro.
     */
    private JFrame frame;

    public FormServiziDocente() {

        /*
         * Listener Conferma: guardie sull'input qui nel Boundary, controller
         * static per la ricerca + la lista delle classi. Su successo apre il
         * popup FormSceltaClasse modale.
         */
        buttonConferma.addActionListener(e -> {

            pulisciErrore();

            String nome = fieldNome.getText().trim();
            String cognome = fieldCognome.getText().trim();

            if (nome.isEmpty() || cognome.isEmpty()) {
                mostraErrore("Inserire nome e cognome");
                return;
            }

            Docente docente = GestoreServiziDocente.cercaDocente(nome, cognome);
            if (docente == null) {
                mostraErrore("Docente non trovato");
                return;
            }

            /*
            Questo richiama la ricerca filtrata Custom creata da noi nel
            GestorePersistenza, tramite questo meccanismo

            GestoreServiziDocente (Controller) -> GestoreRegistroDocente (Entity) ->
            GestorePersistenza(Database)

             */

            List<ClasseVirtuale> classi = GestoreServiziDocente.classiDi(docente);
            if (classi.isEmpty()) {
                mostraErrore("Nessuna classe associata a questo docente");
                return;
            }

            apriSceltaClasse(docente, classi);
        });
    }

    /*
     * Popup modale per la scelta classe. Su Conferma chiude dialog +
     * login e apre la gestione registro: navigazione Boundary -> Boundary.
     */
    private void apriSceltaClasse(Docente docente, List<ClasseVirtuale> classi) {
        FormSceltaClasse formScelta = new FormSceltaClasse();
        formScelta.setClassi(classi);
        formScelta.addConfermaListener(e -> {
            ClasseVirtuale scelta = formScelta.getClasseSelezionata();
            formScelta.chiudiDialog();
            frame.dispose();

            /*
            Quando tutto andrà a buon fine, aprirà la finestra di Gestione del Registro
            che si dividerà poi in due sotto-panel
             */

            new FormGestioneRegistro().apriGestioneRegistro(docente, scelta);
        });
        formScelta.apriDialog(frame);
    }

    /*
     * Entry point del Boundary. Crea il JFrame, lo mostra; il listener
     * Conferma (registrato nel costruttore) prende in carico il resto.
     */
    public JFrame apriFormServiziDocente() {
        frame = new JFrame("Accesso Docente");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(panel1);
        frame.setSize(500, 400);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    public void mostraErrore(String messaggio) {
        labelErrore.setText(messaggio);
    }

    public void pulisciErrore() {
        labelErrore.setText(" ");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 1, new Insets(25, 30, 25, 30), 0, 20));
        final JLabel labelTitolo = new JLabel();
        labelTitolo.setFont(new Font("SansSerif", Font.BOLD, 24));
        labelTitolo.setText("Accesso Docente");
        panel1.add(labelTitolo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), 15, 12));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel labelNome = new JLabel();
        labelNome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        labelNome.setText("Nome:");
        panel2.add(labelNome, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldNome = new JTextField();
        fieldNome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        panel2.add(fieldNome, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(250, 30), null, 0, false));
        final JLabel labelCognome = new JLabel();
        labelCognome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        labelCognome.setText("Cognome:");
        panel2.add(labelCognome, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldCognome = new JTextField();
        fieldCognome.setFont(new Font("SansSerif", Font.PLAIN, 14));
        panel2.add(fieldCognome, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(250, 30), null, 0, false));
        labelErrore = new JLabel();
        labelErrore.setFont(new Font("SansSerif", Font.ITALIC, 13));
        labelErrore.setForeground(new Color(-65536));
        labelErrore.setText(" ");
        panel1.add(labelErrore, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonConferma = new JButton();
        buttonConferma.setFont(new Font("SansSerif", Font.BOLD, 16));
        buttonConferma.setText("Conferma");
        panel1.add(buttonConferma, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 45), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}