package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

public class FormSceltaUtente {
    private JPanel panel1;
    private JButton buttonStudente;
    private JButton buttonDocente;

    /*
     * Restituisce il pannello principale del form
     * Il Main lo usera' per inserirlo dentro al JFrame
     */
    public JComponent getPanel() {
        return panel1;
    }

    /*
     * Aggancia un listener al click del bottone "Studente"
     * Il Main lo usera' per avviare il flow studente
     */
    public void addStudenteListener(ActionListener listener) {
        buttonStudente.addActionListener(listener);
    }

    /*
     * Aggancia un listener al click del bottone "Docente"
     * Il Main lo usera' per avviare il flow docente
     */
    public void addDocenteListener(ActionListener listener) {
        buttonDocente.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(20, 20, 20, 20), -1, 20));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 30, 0, true, false));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonStudente = new JButton();
        buttonStudente.setFont(new Font("SansSerif", Font.BOLD, 22));
        buttonStudente.setText("Studente");
        panel2.add(buttonStudente, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(250, 150), null, 0, false));
        buttonDocente = new JButton();
        buttonDocente.setFont(new Font("SansSerif", Font.BOLD, 22));
        buttonDocente.setText("Docente");
        panel2.add(buttonDocente, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(250, 150), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setFont(new Font("SansSerif", Font.BOLD, 26));
        label1.setText("Come vuoi accedere?");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
