package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/*
 * Boundary di root: la prima schermata che vede l'utente
 * ("Come vuoi accedere?" + bottoni Studente/Docente).
 *
 *  Qui gestiamo semplicemente l'instradamento verso utilizzo delle feature per
 * Studente o Docente, non sarà possibile tornare indietro una volta scelto
 */
public class FormSceltaUtente {
    private JPanel panel1;
    private JButton buttonStudente;
    private JButton buttonDocente;

    /*
     * JFrame "di proprieta'" del Boundary, creato in apriSceltaUtente().
     * Tenerlo come campo permette ai listener (registrati nel costruttore)
     * di chiamarlo al momento del click.
     */
    private JFrame frame;

    public FormSceltaUtente() {
        buttonStudente.addActionListener(e -> {
            frame.dispose();
            new FormServiziStudente().apriFormServiziStudente();
        });
        buttonDocente.addActionListener(e -> {
            frame.dispose();
            new FormServiziDocente().apriFormServiziDocente();
        });
    }

    /*
     * Entry point del Boundary: crea il JFrame root e lo mostra.
     * Chiamato direttamente da MainAvviaApp dentro l'EDT.
     */
    public JFrame apriSceltaUtente() {
        frame = new JFrame("Sistema Registro Elettronico");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(panel1);
        frame.setSize(700, 350);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(20, 20, 20, 20), -1, 20));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 30, 0, true, false));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonStudente = new JButton();
        buttonStudente.setFont(new Font("SansSerif", Font.BOLD, 22));
        buttonStudente.setText("Studente");
        panel2.add(buttonStudente, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(250, 150), null, 0, false));
        buttonDocente = new JButton();
        buttonDocente.setFont(new Font("SansSerif", Font.BOLD, 22));
        buttonDocente.setText("Docente");
        panel2.add(buttonDocente, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(250, 150), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setFont(new Font("SansSerif", Font.BOLD, 26));
        label1.setText("Come vuoi accedere?");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
