package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import entity.ClasseVirtuale;
import entity.Studente;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.Locale;

/*
 * Form di visualizzazione del profilo studente.
 *
 * Per ora mostra solo una label "Profilo di Nome Cognome" e un bottone
 * "Indietro" per tornare alla schermata di selezione studente.
 * Verra' arricchita (voti, lezioni, compiti, ecc.) disegnando i nuovi
 * componenti direttamente nel .form via IntelliJ GUI Designer.
 */
public class FormVisualizzazioneProfilo {

    private JPanel panel1;
    private JButton buttonBack;
    private JLabel labelProfilo;

    public JComponent getPanel() {
        return panel1;
    }

    /*
     * Imposta lo studente da visualizzare.
     * Per ora aggiorna solo la label di intestazione.
     */
    public void mostraProfilo(Studente studente, ClasseVirtuale classe) {
        labelProfilo.setText("Profilo di " + studente.getNome() + " " + studente.getCognome());
        /*
        TODO: Da implementare la Visualizzazione
         */
    }

    /*
     * Aggancia un listener al click del bottone "Indietro".
     * Il controller lo usera' per tornare alla schermata di scelta studente.
     */
    public void addBackListener(ActionListener listener) {
        buttonBack.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(30, 30, 30, 30), 0, 15));
        panel1.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        buttonBack = new JButton();
        Font buttonBackFont = this.$$$getFont$$$("SansSerif", -1, 12, buttonBack.getFont());
        if (buttonBackFont != null) buttonBack.setFont(buttonBackFont);
        buttonBack.setText("Indietro");
        panel1.add(buttonBack, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(80, 24), null, 0, false));
        labelProfilo = new JLabel();
        Font labelProfiloFont = this.$$$getFont$$$("SansSerif", Font.BOLD, 22, labelProfilo.getFont());
        if (labelProfiloFont != null) labelProfilo.setFont(labelProfiloFont);
        labelProfilo.setHorizontalAlignment(0);
        labelProfilo.setText("Profilo");
        panel1.add(labelProfilo, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
