package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/*
 * Form principale del flow docente.
 *
 * In alto: bottone "Indietro" (torna alla scelta classe/docente).
 * Sotto: due JToggleButton ("Aggiorna Registro" / "Consulta Registro")
 * raggruppati in ButtonGroup (uno sempre selezionato).
 * In basso: un pannello "contenuto" che mostra alternativamente il
 * sotto-pannello di aggiornamento o quello di consultazione.
 *
 * I due sotto-pannelli sono per ora placeholder vuoti (i casi d'uso
 * veri verranno implementati nello step successivo).
 */
public class FormGestioneRegistro {

    private JPanel panel1;
    private JButton buttonBack;
    private JToggleButton toggleAggiorna;
    private JToggleButton toggleConsulta;
    private JPanel panelContenuto;

    /*
     * Sotto-pannelli costruiti programmaticamente. Restano placeholder
     * finche' non implementeremo i due casi d'uso.
     */
    private final JPanel panelAggiorna = creaPlaceholder("Aggiornamento Registro — da implementare");
    private final JPanel panelConsulta = creaPlaceholder("Consultazione Registro — da implementare");

    public FormGestioneRegistro() {

        ButtonGroup gruppo = new ButtonGroup();
        gruppo.add(toggleAggiorna);
        gruppo.add(toggleConsulta);

        // Stato iniziale: vista "Aggiorna" attiva
        toggleAggiorna.setSelected(true);
        mostraSotto(panelAggiorna);

        toggleAggiorna.addActionListener(e -> mostraSotto(panelAggiorna));
        toggleConsulta.addActionListener(e -> mostraSotto(panelConsulta));
    }

    public JComponent getPanel() {
        return panel1;
    }

    /*
     * Aggancia un listener al click del bottone "Indietro".
     * Il controller lo usera' per tornare alla scelta classe/docente.
     */
    public void addBackListener(ActionListener listener) {
        buttonBack.addActionListener(listener);
    }

    /*
     * Sostituisce il contenuto di panelContenuto con il sotto-pannello
     * richiesto. revalidate + repaint sono necessari perche' stiamo
     * cambiando i figli di un container gia' visibile.
     */
    private void mostraSotto(JPanel sotto) {
        panelContenuto.removeAll();
        panelContenuto.add(sotto, BorderLayout.CENTER);
        panelContenuto.revalidate();
        panelContenuto.repaint();
    }

    private static JPanel creaPlaceholder(String testo) {
        JPanel p = new JPanel(new BorderLayout());
        JLabel l = new JLabel(testo, SwingConstants.CENTER);
        l.setFont(new Font("SansSerif", Font.ITALIC, 16));
        l.setForeground(new Color(120, 120, 120));
        p.add(l, BorderLayout.CENTER);
        return p;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 1, new Insets(25, 30, 25, 30), 0, 15));
        buttonBack = new JButton();
        buttonBack.setFont(new Font("SansSerif", Font.PLAIN, 12));
        buttonBack.setText("Indietro");
        panel1.add(buttonBack, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(80, 24), null, 0, false));
        final JPanel togglebar = new JPanel();
        togglebar.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 15, 0, true, false));
        panel1.add(togglebar, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        toggleAggiorna = new JToggleButton();
        toggleAggiorna.setFont(new Font("SansSerif", Font.BOLD, 14));
        toggleAggiorna.setText("Aggiorna Registro");
        togglebar.add(toggleAggiorna, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));
        toggleConsulta = new JToggleButton();
        toggleConsulta.setFont(new Font("SansSerif", Font.BOLD, 14));
        toggleConsulta.setText("Consulta Registro");
        togglebar.add(toggleConsulta, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));
        panelContenuto = new JPanel();
        panelContenuto.setLayout(new BorderLayout(0, 0));
        panelContenuto.setBorder(BorderFactory.createLineBorder(new Color(-3355444)));
        panel1.add(panelContenuto, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
